# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "9b0e722c7ca6973901115d496d97ff97"
application_url = "https://active-unto-armstrong-tion.trycloudflare.com"
embedded = true
name = "app"
handle = "app-1010"

[build]
include_config_on_deploy = true
dev_store_url = "store4app.myshopify.com"
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://active-unto-armstrong-tion.trycloudflare.com/auth/callback",
  "https://active-unto-armstrong-tion.trycloudflare.com/auth/shopify/callback",
  "https://active-unto-armstrong-tion.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
